/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence;


import cn.luixtech.passport.server.persistence.tables.Oauth2Authorization;
import cn.luixtech.passport.server.persistence.tables.Oauth2AuthorizationConsent;
import cn.luixtech.passport.server.persistence.tables.Oauth2RegisteredClient;
import cn.luixtech.passport.server.persistence.tables.SpringSession;
import cn.luixtech.passport.server.persistence.tables.SpringSessionAttributes;
import cn.luixtech.passport.server.persistence.tables.User;
import cn.luixtech.passport.server.persistence.tables.UserAuthenticationEvent;
import cn.luixtech.passport.server.persistence.tables.UserAuthority;
import cn.luixtech.passport.server.persistence.tables.UserLogin;
import cn.luixtech.passport.server.persistence.tables.UserPermission;
import cn.luixtech.passport.server.persistence.tables.UserPhoto;
import cn.luixtech.passport.server.persistence.tables.UserPreference;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LuixPassport extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>luix-passport</code>
     */
    public static final LuixPassport LUIX_PASSPORT = new LuixPassport();

    /**
     * The table <code>luix-passport.oauth2_authorization</code>.
     */
    public final Oauth2Authorization OAUTH2_AUTHORIZATION = Oauth2Authorization.OAUTH2_AUTHORIZATION;

    /**
     * The table <code>luix-passport.oauth2_authorization_consent</code>.
     */
    public final Oauth2AuthorizationConsent OAUTH2_AUTHORIZATION_CONSENT = Oauth2AuthorizationConsent.OAUTH2_AUTHORIZATION_CONSENT;

    /**
     * The table <code>luix-passport.oauth2_registered_client</code>.
     */
    public final Oauth2RegisteredClient OAUTH2_REGISTERED_CLIENT = Oauth2RegisteredClient.OAUTH2_REGISTERED_CLIENT;

    /**
     * The table <code>luix-passport.spring_session</code>.
     */
    public final SpringSession SPRING_SESSION = SpringSession.SPRING_SESSION;

    /**
     * The table <code>luix-passport.spring_session_attributes</code>.
     */
    public final SpringSessionAttributes SPRING_SESSION_ATTRIBUTES = SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES;

    /**
     * The table <code>luix-passport.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>luix-passport.user_authentication_event</code>.
     */
    public final UserAuthenticationEvent USER_AUTHENTICATION_EVENT = UserAuthenticationEvent.USER_AUTHENTICATION_EVENT;

    /**
     * The table <code>luix-passport.user_authority</code>.
     */
    public final UserAuthority USER_AUTHORITY = UserAuthority.USER_AUTHORITY;

    /**
     * The table <code>luix-passport.user_login</code>.
     */
    public final UserLogin USER_LOGIN = UserLogin.USER_LOGIN;

    /**
     * The table <code>luix-passport.user_permission</code>.
     */
    public final UserPermission USER_PERMISSION = UserPermission.USER_PERMISSION;

    /**
     * The table <code>luix-passport.user_photo</code>.
     */
    public final UserPhoto USER_PHOTO = UserPhoto.USER_PHOTO;

    /**
     * The table <code>luix-passport.user_preference</code>.
     */
    public final UserPreference USER_PREFERENCE = UserPreference.USER_PREFERENCE;

    /**
     * No further instances allowed
     */
    private LuixPassport() {
        super("luix-passport", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Oauth2Authorization.OAUTH2_AUTHORIZATION,
            Oauth2AuthorizationConsent.OAUTH2_AUTHORIZATION_CONSENT,
            Oauth2RegisteredClient.OAUTH2_REGISTERED_CLIENT,
            SpringSession.SPRING_SESSION,
            SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES,
            User.USER,
            UserAuthenticationEvent.USER_AUTHENTICATION_EVENT,
            UserAuthority.USER_AUTHORITY,
            UserLogin.USER_LOGIN,
            UserPermission.USER_PERMISSION,
            UserPhoto.USER_PHOTO,
            UserPreference.USER_PREFERENCE
        );
    }
}
