/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence;


import cn.luixtech.passport.server.persistence.tables.Oauth2Authorization;
import cn.luixtech.passport.server.persistence.tables.Oauth2AuthorizationConsent;
import cn.luixtech.passport.server.persistence.tables.Oauth2RegisteredClient;
import cn.luixtech.passport.server.persistence.tables.User;
import cn.luixtech.passport.server.persistence.tables.UserPermission;
import cn.luixtech.passport.server.persistence.tables.UserRole;


/**
 * Convenience access to all tables in luix-passport2.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>luix-passport2.oauth2_authorization</code>.
     */
    public static final Oauth2Authorization OAUTH2_AUTHORIZATION = Oauth2Authorization.OAUTH2_AUTHORIZATION;

    /**
     * The table <code>luix-passport2.oauth2_authorization_consent</code>.
     */
    public static final Oauth2AuthorizationConsent OAUTH2_AUTHORIZATION_CONSENT = Oauth2AuthorizationConsent.OAUTH2_AUTHORIZATION_CONSENT;

    /**
     * The table <code>luix-passport2.oauth2_registered_client</code>.
     */
    public static final Oauth2RegisteredClient OAUTH2_REGISTERED_CLIENT = Oauth2RegisteredClient.OAUTH2_REGISTERED_CLIENT;

    /**
     * The table <code>luix-passport2.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>luix-passport2.user_permission</code>.
     */
    public static final UserPermission USER_PERMISSION = UserPermission.USER_PERMISSION;

    /**
     * The table <code>luix-passport2.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
