/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DataDict implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String num;
    private String categoryCode;
    private String dictCode;
    private String dictName;
    private String remark;
    private Boolean enabled;
    private String createdBy;
    private LocalDateTime createdTime;
    private String modifiedBy;
    private LocalDateTime modifiedTime;

    public DataDict() {}

    public DataDict(DataDict value) {
        this.id = value.id;
        this.num = value.num;
        this.categoryCode = value.categoryCode;
        this.dictCode = value.dictCode;
        this.dictName = value.dictName;
        this.remark = value.remark;
        this.enabled = value.enabled;
        this.createdBy = value.createdBy;
        this.createdTime = value.createdTime;
        this.modifiedBy = value.modifiedBy;
        this.modifiedTime = value.modifiedTime;
    }

    public DataDict(
        String id,
        String num,
        String categoryCode,
        String dictCode,
        String dictName,
        String remark,
        Boolean enabled,
        String createdBy,
        LocalDateTime createdTime,
        String modifiedBy,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.num = num;
        this.categoryCode = categoryCode;
        this.dictCode = dictCode;
        this.dictName = dictName;
        this.remark = remark;
        this.enabled = enabled;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.modifiedBy = modifiedBy;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>luix-passport.data_dict.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>luix-passport.data_dict.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>luix-passport.data_dict.num</code>.
     */
    public String getNum() {
        return this.num;
    }

    /**
     * Setter for <code>luix-passport.data_dict.num</code>.
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * Getter for <code>luix-passport.data_dict.category_code</code>.
     */
    public String getCategoryCode() {
        return this.categoryCode;
    }

    /**
     * Setter for <code>luix-passport.data_dict.category_code</code>.
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    /**
     * Getter for <code>luix-passport.data_dict.dict_code</code>.
     */
    public String getDictCode() {
        return this.dictCode;
    }

    /**
     * Setter for <code>luix-passport.data_dict.dict_code</code>.
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode;
    }

    /**
     * Getter for <code>luix-passport.data_dict.dict_name</code>.
     */
    public String getDictName() {
        return this.dictName;
    }

    /**
     * Setter for <code>luix-passport.data_dict.dict_name</code>.
     */
    public void setDictName(String dictName) {
        this.dictName = dictName;
    }

    /**
     * Getter for <code>luix-passport.data_dict.remark</code>.
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * Setter for <code>luix-passport.data_dict.remark</code>.
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * Getter for <code>luix-passport.data_dict.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>luix-passport.data_dict.enabled</code>.
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Getter for <code>luix-passport.data_dict.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>luix-passport.data_dict.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>luix-passport.data_dict.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Setter for <code>luix-passport.data_dict.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * Getter for <code>luix-passport.data_dict.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>luix-passport.data_dict.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>luix-passport.data_dict.modified_time</code>.
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>luix-passport.data_dict.modified_time</code>.
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DataDict other = (DataDict) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.num == null) {
            if (other.num != null)
                return false;
        }
        else if (!this.num.equals(other.num))
            return false;
        if (this.categoryCode == null) {
            if (other.categoryCode != null)
                return false;
        }
        else if (!this.categoryCode.equals(other.categoryCode))
            return false;
        if (this.dictCode == null) {
            if (other.dictCode != null)
                return false;
        }
        else if (!this.dictCode.equals(other.dictCode))
            return false;
        if (this.dictName == null) {
            if (other.dictName != null)
                return false;
        }
        else if (!this.dictName.equals(other.dictName))
            return false;
        if (this.remark == null) {
            if (other.remark != null)
                return false;
        }
        else if (!this.remark.equals(other.remark))
            return false;
        if (this.enabled == null) {
            if (other.enabled != null)
                return false;
        }
        else if (!this.enabled.equals(other.enabled))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdTime == null) {
            if (other.createdTime != null)
                return false;
        }
        else if (!this.createdTime.equals(other.createdTime))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.modifiedTime == null) {
            if (other.modifiedTime != null)
                return false;
        }
        else if (!this.modifiedTime.equals(other.modifiedTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.num == null) ? 0 : this.num.hashCode());
        result = prime * result + ((this.categoryCode == null) ? 0 : this.categoryCode.hashCode());
        result = prime * result + ((this.dictCode == null) ? 0 : this.dictCode.hashCode());
        result = prime * result + ((this.dictName == null) ? 0 : this.dictName.hashCode());
        result = prime * result + ((this.remark == null) ? 0 : this.remark.hashCode());
        result = prime * result + ((this.enabled == null) ? 0 : this.enabled.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdTime == null) ? 0 : this.createdTime.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.modifiedTime == null) ? 0 : this.modifiedTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DataDict (");

        sb.append(id);
        sb.append(", ").append(num);
        sb.append(", ").append(categoryCode);
        sb.append(", ").append(dictCode);
        sb.append(", ").append(dictName);
        sb.append(", ").append(remark);
        sb.append(", ").append(enabled);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
