/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DataDict implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String categoryCode;
    private String dictCode;
    private String dictName;
    private String desc;
    private Boolean enabled;

    public DataDict() {}

    public DataDict(DataDict value) {
        this.id = value.id;
        this.categoryCode = value.categoryCode;
        this.dictCode = value.dictCode;
        this.dictName = value.dictName;
        this.desc = value.desc;
        this.enabled = value.enabled;
    }

    public DataDict(
        String id,
        String categoryCode,
        String dictCode,
        String dictName,
        String desc,
        Boolean enabled
    ) {
        this.id = id;
        this.categoryCode = categoryCode;
        this.dictCode = dictCode;
        this.dictName = dictName;
        this.desc = desc;
        this.enabled = enabled;
    }

    /**
     * Getter for <code>luix-passport.data_dict.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>luix-passport.data_dict.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>luix-passport.data_dict.category_code</code>.
     */
    public String getCategoryCode() {
        return this.categoryCode;
    }

    /**
     * Setter for <code>luix-passport.data_dict.category_code</code>.
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    /**
     * Getter for <code>luix-passport.data_dict.dict_code</code>.
     */
    public String getDictCode() {
        return this.dictCode;
    }

    /**
     * Setter for <code>luix-passport.data_dict.dict_code</code>.
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode;
    }

    /**
     * Getter for <code>luix-passport.data_dict.dict_name</code>.
     */
    public String getDictName() {
        return this.dictName;
    }

    /**
     * Setter for <code>luix-passport.data_dict.dict_name</code>.
     */
    public void setDictName(String dictName) {
        this.dictName = dictName;
    }

    /**
     * Getter for <code>luix-passport.data_dict.desc</code>.
     */
    public String getDesc() {
        return this.desc;
    }

    /**
     * Setter for <code>luix-passport.data_dict.desc</code>.
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * Getter for <code>luix-passport.data_dict.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>luix-passport.data_dict.enabled</code>.
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DataDict other = (DataDict) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.categoryCode == null) {
            if (other.categoryCode != null)
                return false;
        }
        else if (!this.categoryCode.equals(other.categoryCode))
            return false;
        if (this.dictCode == null) {
            if (other.dictCode != null)
                return false;
        }
        else if (!this.dictCode.equals(other.dictCode))
            return false;
        if (this.dictName == null) {
            if (other.dictName != null)
                return false;
        }
        else if (!this.dictName.equals(other.dictName))
            return false;
        if (this.desc == null) {
            if (other.desc != null)
                return false;
        }
        else if (!this.desc.equals(other.desc))
            return false;
        if (this.enabled == null) {
            if (other.enabled != null)
                return false;
        }
        else if (!this.enabled.equals(other.enabled))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.categoryCode == null) ? 0 : this.categoryCode.hashCode());
        result = prime * result + ((this.dictCode == null) ? 0 : this.dictCode.hashCode());
        result = prime * result + ((this.dictName == null) ? 0 : this.dictName.hashCode());
        result = prime * result + ((this.desc == null) ? 0 : this.desc.hashCode());
        result = prime * result + ((this.enabled == null) ? 0 : this.enabled.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DataDict (");

        sb.append(id);
        sb.append(", ").append(categoryCode);
        sb.append(", ").append(dictCode);
        sb.append(", ").append(dictName);
        sb.append(", ").append(desc);
        sb.append(", ").append(enabled);

        sb.append(")");
        return sb.toString();
    }
}
