/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAuthenticationEvent implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        id;
    private String        userId;
    private String        event;
    private String        description;
    private LocalDateTime createdTime;

    public UserAuthenticationEvent() {}

    public UserAuthenticationEvent(UserAuthenticationEvent value) {
        this.id = value.id;
        this.userId = value.userId;
        this.event = value.event;
        this.description = value.description;
        this.createdTime = value.createdTime;
    }

    public UserAuthenticationEvent(
        String        id,
        String        userId,
        String        event,
        String        description,
        LocalDateTime createdTime
    ) {
        this.id = id;
        this.userId = userId;
        this.event = event;
        this.description = description;
        this.createdTime = createdTime;
    }

    /**
     * Getter for <code>luix-passport.user_authentication_event.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>luix-passport.user_authentication_event.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>luix-passport.user_authentication_event.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>luix-passport.user_authentication_event.user_id</code>.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>luix-passport.user_authentication_event.event</code>.
     */
    public String getEvent() {
        return this.event;
    }

    /**
     * Setter for <code>luix-passport.user_authentication_event.event</code>.
     */
    public void setEvent(String event) {
        this.event = event;
    }

    /**
     * Getter for <code>luix-passport.user_authentication_event.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>luix-passport.user_authentication_event.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>luix-passport.user_authentication_event.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Setter for <code>luix-passport.user_authentication_event.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserAuthenticationEvent other = (UserAuthenticationEvent) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (event == null) {
            if (other.event != null)
                return false;
        }
        else if (!event.equals(other.event))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (createdTime == null) {
            if (other.createdTime != null)
                return false;
        }
        else if (!createdTime.equals(other.createdTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.event == null) ? 0 : this.event.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.createdTime == null) ? 0 : this.createdTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAuthenticationEvent (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(event);
        sb.append(", ").append(description);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
