/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String username;
    private String email;
    private String mobileNo;
    private String firstName;
    private String lastName;
    private String passwordHash;
    private String activationCode;
    private String resetCode;
    private LocalDateTime resetTime;
    private Boolean profilePhotoEnabled;
    private String remarks;
    private Boolean activated;
    private Boolean enabled;
    private LocalDateTime accountExpiresAt;
    private LocalDateTime passwordExpiresAt;
    private String locale;
    private String timeZone;
    private String dateFormat;
    private String createdBy;
    private LocalDateTime createdTime;
    private String modifiedBy;
    private LocalDateTime modifiedTime;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.username = value.username;
        this.email = value.email;
        this.mobileNo = value.mobileNo;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.passwordHash = value.passwordHash;
        this.activationCode = value.activationCode;
        this.resetCode = value.resetCode;
        this.resetTime = value.resetTime;
        this.profilePhotoEnabled = value.profilePhotoEnabled;
        this.remarks = value.remarks;
        this.activated = value.activated;
        this.enabled = value.enabled;
        this.accountExpiresAt = value.accountExpiresAt;
        this.passwordExpiresAt = value.passwordExpiresAt;
        this.locale = value.locale;
        this.timeZone = value.timeZone;
        this.dateFormat = value.dateFormat;
        this.createdBy = value.createdBy;
        this.createdTime = value.createdTime;
        this.modifiedBy = value.modifiedBy;
        this.modifiedTime = value.modifiedTime;
    }

    public User(
        String id,
        String username,
        String email,
        String mobileNo,
        String firstName,
        String lastName,
        String passwordHash,
        String activationCode,
        String resetCode,
        LocalDateTime resetTime,
        Boolean profilePhotoEnabled,
        String remarks,
        Boolean activated,
        Boolean enabled,
        LocalDateTime accountExpiresAt,
        LocalDateTime passwordExpiresAt,
        String locale,
        String timeZone,
        String dateFormat,
        String createdBy,
        LocalDateTime createdTime,
        String modifiedBy,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.mobileNo = mobileNo;
        this.firstName = firstName;
        this.lastName = lastName;
        this.passwordHash = passwordHash;
        this.activationCode = activationCode;
        this.resetCode = resetCode;
        this.resetTime = resetTime;
        this.profilePhotoEnabled = profilePhotoEnabled;
        this.remarks = remarks;
        this.activated = activated;
        this.enabled = enabled;
        this.accountExpiresAt = accountExpiresAt;
        this.passwordExpiresAt = passwordExpiresAt;
        this.locale = locale;
        this.timeZone = timeZone;
        this.dateFormat = dateFormat;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.modifiedBy = modifiedBy;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>luix-passport.user.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>luix-passport.user.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>luix-passport.user.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>luix-passport.user.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>luix-passport.user.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>luix-passport.user.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>luix-passport.user.mobile_no</code>.
     */
    public String getMobileNo() {
        return this.mobileNo;
    }

    /**
     * Setter for <code>luix-passport.user.mobile_no</code>.
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    /**
     * Getter for <code>luix-passport.user.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>luix-passport.user.first_name</code>.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>luix-passport.user.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>luix-passport.user.last_name</code>.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>luix-passport.user.password_hash</code>.
     */
    public String getPasswordHash() {
        return this.passwordHash;
    }

    /**
     * Setter for <code>luix-passport.user.password_hash</code>.
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * Getter for <code>luix-passport.user.activation_code</code>.
     */
    public String getActivationCode() {
        return this.activationCode;
    }

    /**
     * Setter for <code>luix-passport.user.activation_code</code>.
     */
    public void setActivationCode(String activationCode) {
        this.activationCode = activationCode;
    }

    /**
     * Getter for <code>luix-passport.user.reset_code</code>.
     */
    public String getResetCode() {
        return this.resetCode;
    }

    /**
     * Setter for <code>luix-passport.user.reset_code</code>.
     */
    public void setResetCode(String resetCode) {
        this.resetCode = resetCode;
    }

    /**
     * Getter for <code>luix-passport.user.reset_time</code>.
     */
    public LocalDateTime getResetTime() {
        return this.resetTime;
    }

    /**
     * Setter for <code>luix-passport.user.reset_time</code>.
     */
    public void setResetTime(LocalDateTime resetTime) {
        this.resetTime = resetTime;
    }

    /**
     * Getter for <code>luix-passport.user.profile_photo_enabled</code>.
     */
    public Boolean getProfilePhotoEnabled() {
        return this.profilePhotoEnabled;
    }

    /**
     * Setter for <code>luix-passport.user.profile_photo_enabled</code>.
     */
    public void setProfilePhotoEnabled(Boolean profilePhotoEnabled) {
        this.profilePhotoEnabled = profilePhotoEnabled;
    }

    /**
     * Getter for <code>luix-passport.user.remarks</code>.
     */
    public String getRemarks() {
        return this.remarks;
    }

    /**
     * Setter for <code>luix-passport.user.remarks</code>.
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * Getter for <code>luix-passport.user.activated</code>.
     */
    public Boolean getActivated() {
        return this.activated;
    }

    /**
     * Setter for <code>luix-passport.user.activated</code>.
     */
    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    /**
     * Getter for <code>luix-passport.user.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>luix-passport.user.enabled</code>.
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Getter for <code>luix-passport.user.account_expires_at</code>.
     */
    public LocalDateTime getAccountExpiresAt() {
        return this.accountExpiresAt;
    }

    /**
     * Setter for <code>luix-passport.user.account_expires_at</code>.
     */
    public void setAccountExpiresAt(LocalDateTime accountExpiresAt) {
        this.accountExpiresAt = accountExpiresAt;
    }

    /**
     * Getter for <code>luix-passport.user.password_expires_at</code>.
     */
    public LocalDateTime getPasswordExpiresAt() {
        return this.passwordExpiresAt;
    }

    /**
     * Setter for <code>luix-passport.user.password_expires_at</code>.
     */
    public void setPasswordExpiresAt(LocalDateTime passwordExpiresAt) {
        this.passwordExpiresAt = passwordExpiresAt;
    }

    /**
     * Getter for <code>luix-passport.user.locale</code>.
     */
    public String getLocale() {
        return this.locale;
    }

    /**
     * Setter for <code>luix-passport.user.locale</code>.
     */
    public void setLocale(String locale) {
        this.locale = locale;
    }

    /**
     * Getter for <code>luix-passport.user.time_zone</code>.
     */
    public String getTimeZone() {
        return this.timeZone;
    }

    /**
     * Setter for <code>luix-passport.user.time_zone</code>.
     */
    public void setTimeZone(String timeZone) {
        this.timeZone = timeZone;
    }

    /**
     * Getter for <code>luix-passport.user.date_format</code>.
     */
    public String getDateFormat() {
        return this.dateFormat;
    }

    /**
     * Setter for <code>luix-passport.user.date_format</code>.
     */
    public void setDateFormat(String dateFormat) {
        this.dateFormat = dateFormat;
    }

    /**
     * Getter for <code>luix-passport.user.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>luix-passport.user.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>luix-passport.user.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Setter for <code>luix-passport.user.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * Getter for <code>luix-passport.user.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>luix-passport.user.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>luix-passport.user.modified_time</code>.
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>luix-passport.user.modified_time</code>.
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final User other = (User) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.mobileNo == null) {
            if (other.mobileNo != null)
                return false;
        }
        else if (!this.mobileNo.equals(other.mobileNo))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.passwordHash == null) {
            if (other.passwordHash != null)
                return false;
        }
        else if (!this.passwordHash.equals(other.passwordHash))
            return false;
        if (this.activationCode == null) {
            if (other.activationCode != null)
                return false;
        }
        else if (!this.activationCode.equals(other.activationCode))
            return false;
        if (this.resetCode == null) {
            if (other.resetCode != null)
                return false;
        }
        else if (!this.resetCode.equals(other.resetCode))
            return false;
        if (this.resetTime == null) {
            if (other.resetTime != null)
                return false;
        }
        else if (!this.resetTime.equals(other.resetTime))
            return false;
        if (this.profilePhotoEnabled == null) {
            if (other.profilePhotoEnabled != null)
                return false;
        }
        else if (!this.profilePhotoEnabled.equals(other.profilePhotoEnabled))
            return false;
        if (this.remarks == null) {
            if (other.remarks != null)
                return false;
        }
        else if (!this.remarks.equals(other.remarks))
            return false;
        if (this.activated == null) {
            if (other.activated != null)
                return false;
        }
        else if (!this.activated.equals(other.activated))
            return false;
        if (this.enabled == null) {
            if (other.enabled != null)
                return false;
        }
        else if (!this.enabled.equals(other.enabled))
            return false;
        if (this.accountExpiresAt == null) {
            if (other.accountExpiresAt != null)
                return false;
        }
        else if (!this.accountExpiresAt.equals(other.accountExpiresAt))
            return false;
        if (this.passwordExpiresAt == null) {
            if (other.passwordExpiresAt != null)
                return false;
        }
        else if (!this.passwordExpiresAt.equals(other.passwordExpiresAt))
            return false;
        if (this.locale == null) {
            if (other.locale != null)
                return false;
        }
        else if (!this.locale.equals(other.locale))
            return false;
        if (this.timeZone == null) {
            if (other.timeZone != null)
                return false;
        }
        else if (!this.timeZone.equals(other.timeZone))
            return false;
        if (this.dateFormat == null) {
            if (other.dateFormat != null)
                return false;
        }
        else if (!this.dateFormat.equals(other.dateFormat))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdTime == null) {
            if (other.createdTime != null)
                return false;
        }
        else if (!this.createdTime.equals(other.createdTime))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.modifiedTime == null) {
            if (other.modifiedTime != null)
                return false;
        }
        else if (!this.modifiedTime.equals(other.modifiedTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.mobileNo == null) ? 0 : this.mobileNo.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.passwordHash == null) ? 0 : this.passwordHash.hashCode());
        result = prime * result + ((this.activationCode == null) ? 0 : this.activationCode.hashCode());
        result = prime * result + ((this.resetCode == null) ? 0 : this.resetCode.hashCode());
        result = prime * result + ((this.resetTime == null) ? 0 : this.resetTime.hashCode());
        result = prime * result + ((this.profilePhotoEnabled == null) ? 0 : this.profilePhotoEnabled.hashCode());
        result = prime * result + ((this.remarks == null) ? 0 : this.remarks.hashCode());
        result = prime * result + ((this.activated == null) ? 0 : this.activated.hashCode());
        result = prime * result + ((this.enabled == null) ? 0 : this.enabled.hashCode());
        result = prime * result + ((this.accountExpiresAt == null) ? 0 : this.accountExpiresAt.hashCode());
        result = prime * result + ((this.passwordExpiresAt == null) ? 0 : this.passwordExpiresAt.hashCode());
        result = prime * result + ((this.locale == null) ? 0 : this.locale.hashCode());
        result = prime * result + ((this.timeZone == null) ? 0 : this.timeZone.hashCode());
        result = prime * result + ((this.dateFormat == null) ? 0 : this.dateFormat.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdTime == null) ? 0 : this.createdTime.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.modifiedTime == null) ? 0 : this.modifiedTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(email);
        sb.append(", ").append(mobileNo);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(passwordHash);
        sb.append(", ").append(activationCode);
        sb.append(", ").append(resetCode);
        sb.append(", ").append(resetTime);
        sb.append(", ").append(profilePhotoEnabled);
        sb.append(", ").append(remarks);
        sb.append(", ").append(activated);
        sb.append(", ").append(enabled);
        sb.append(", ").append(accountExpiresAt);
        sb.append(", ").append(passwordExpiresAt);
        sb.append(", ").append(locale);
        sb.append(", ").append(timeZone);
        sb.append(", ").append(dateFormat);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
