/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserPhoto implements Serializable {

    private static final long serialVersionUID = 1L;

    private String userId;
    private byte[] profilePhoto;

    public UserPhoto() {}

    public UserPhoto(UserPhoto value) {
        this.userId = value.userId;
        this.profilePhoto = value.profilePhoto;
    }

    public UserPhoto(
        String userId,
        byte[] profilePhoto
    ) {
        this.userId = userId;
        this.profilePhoto = profilePhoto;
    }

    /**
     * Getter for <code>luix-passport.user_photo.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>luix-passport.user_photo.user_id</code>.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>luix-passport.user_photo.profile_photo</code>.
     */
    public byte[] getProfilePhoto() {
        return this.profilePhoto;
    }

    /**
     * Setter for <code>luix-passport.user_photo.profile_photo</code>.
     */
    public void setProfilePhoto(byte[] profilePhoto) {
        this.profilePhoto = profilePhoto;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserPhoto other = (UserPhoto) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.profilePhoto == null) {
            if (other.profilePhoto != null)
                return false;
        }
        else if (!Arrays.equals(this.profilePhoto, other.profilePhoto))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.profilePhoto == null) ? 0 : Arrays.hashCode(this.profilePhoto));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPhoto (");

        sb.append(userId);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
