/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserPhoto implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private byte[] photo;

    public UserPhoto() {}

    public UserPhoto(UserPhoto value) {
        this.id = value.id;
        this.photo = value.photo;
    }

    public UserPhoto(
        String id,
        byte[] photo
    ) {
        this.id = id;
        this.photo = photo;
    }

    /**
     * Getter for <code>luix-passport.user_photo.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>luix-passport.user_photo.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>luix-passport.user_photo.photo</code>.
     */
    public byte[] getPhoto() {
        return this.photo;
    }

    /**
     * Setter for <code>luix-passport.user_photo.photo</code>.
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserPhoto other = (UserPhoto) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.photo == null) {
            if (other.photo != null)
                return false;
        }
        else if (!Arrays.equals(this.photo, other.photo))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.photo == null) ? 0 : Arrays.hashCode(this.photo));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPhoto (");

        sb.append(id);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
