/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.daos;


import cn.luixtech.passport.server.persistence.tables.Oauth2Authorization;
import cn.luixtech.passport.server.persistence.tables.records.Oauth2AuthorizationRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class Oauth2AuthorizationDao extends DAOImpl<Oauth2AuthorizationRecord, cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization, String> {

    /**
     * Create a new Oauth2AuthorizationDao without any configuration
     */
    public Oauth2AuthorizationDao() {
        super(Oauth2Authorization.OAUTH2_AUTHORIZATION, cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization.class);
    }

    /**
     * Create a new Oauth2AuthorizationDao with an attached configuration
     */
    @Autowired
    public Oauth2AuthorizationDao(Configuration configuration) {
        super(Oauth2Authorization.OAUTH2_AUTHORIZATION, cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization.class, configuration);
    }

    @Override
    public String getId(cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchById(String... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization fetchOneById(String value) {
        return fetchOne(Oauth2Authorization.OAUTH2_AUTHORIZATION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchOptionalById(String value) {
        return fetchOptional(Oauth2Authorization.OAUTH2_AUTHORIZATION.ID, value);
    }

    /**
     * Fetch records that have <code>registered_client_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfRegisteredClientId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.REGISTERED_CLIENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>registered_client_id IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByRegisteredClientId(String... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.REGISTERED_CLIENT_ID, values);
    }

    /**
     * Fetch records that have <code>principal_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfPrincipalName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.PRINCIPAL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>principal_name IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByPrincipalName(String... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.PRINCIPAL_NAME, values);
    }

    /**
     * Fetch records that have <code>authorization_grant_type BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAuthorizationGrantType(String lowerInclusive, String upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZATION_GRANT_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authorization_grant_type IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAuthorizationGrantType(String... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZATION_GRANT_TYPE, values);
    }

    /**
     * Fetch records that have <code>authorized_scopes BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAuthorizedScopes(String lowerInclusive, String upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZED_SCOPES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authorized_scopes IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAuthorizedScopes(String... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZED_SCOPES, values);
    }

    /**
     * Fetch records that have <code>attributes BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAttributes(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.ATTRIBUTES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attributes IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAttributes(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.ATTRIBUTES, values);
    }

    /**
     * Fetch records that have <code>state BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfState(String lowerInclusive, String upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.STATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByState(String... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.STATE, values);
    }

    /**
     * Fetch records that have <code>authorization_code_value BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAuthorizationCodeValue(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZATION_CODE_VALUE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authorization_code_value IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAuthorizationCodeValue(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZATION_CODE_VALUE, values);
    }

    /**
     * Fetch records that have <code>authorization_code_issued_at BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAuthorizationCodeIssuedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZATION_CODE_ISSUED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authorization_code_issued_at IN
     * (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAuthorizationCodeIssuedAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZATION_CODE_ISSUED_AT, values);
    }

    /**
     * Fetch records that have <code>authorization_code_expires_at BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAuthorizationCodeExpiresAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZATION_CODE_EXPIRES_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authorization_code_expires_at IN
     * (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAuthorizationCodeExpiresAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZATION_CODE_EXPIRES_AT, values);
    }

    /**
     * Fetch records that have <code>authorization_code_metadata BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAuthorizationCodeMetadata(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZATION_CODE_METADATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authorization_code_metadata IN
     * (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAuthorizationCodeMetadata(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.AUTHORIZATION_CODE_METADATA, values);
    }

    /**
     * Fetch records that have <code>access_token_value BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAccessTokenValue(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_VALUE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>access_token_value IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAccessTokenValue(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_VALUE, values);
    }

    /**
     * Fetch records that have <code>access_token_issued_at BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAccessTokenIssuedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_ISSUED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>access_token_issued_at IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAccessTokenIssuedAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_ISSUED_AT, values);
    }

    /**
     * Fetch records that have <code>access_token_expires_at BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAccessTokenExpiresAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_EXPIRES_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>access_token_expires_at IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAccessTokenExpiresAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_EXPIRES_AT, values);
    }

    /**
     * Fetch records that have <code>access_token_metadata BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAccessTokenMetadata(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_METADATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>access_token_metadata IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAccessTokenMetadata(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_METADATA, values);
    }

    /**
     * Fetch records that have <code>access_token_type BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAccessTokenType(String lowerInclusive, String upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>access_token_type IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAccessTokenType(String... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_TYPE, values);
    }

    /**
     * Fetch records that have <code>access_token_scopes BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfAccessTokenScopes(String lowerInclusive, String upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_SCOPES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>access_token_scopes IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByAccessTokenScopes(String... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.ACCESS_TOKEN_SCOPES, values);
    }

    /**
     * Fetch records that have <code>oidc_id_token_value BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfOidcIdTokenValue(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.OIDC_ID_TOKEN_VALUE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>oidc_id_token_value IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByOidcIdTokenValue(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.OIDC_ID_TOKEN_VALUE, values);
    }

    /**
     * Fetch records that have <code>oidc_id_token_issued_at BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfOidcIdTokenIssuedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.OIDC_ID_TOKEN_ISSUED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>oidc_id_token_issued_at IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByOidcIdTokenIssuedAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.OIDC_ID_TOKEN_ISSUED_AT, values);
    }

    /**
     * Fetch records that have <code>oidc_id_token_expires_at BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfOidcIdTokenExpiresAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.OIDC_ID_TOKEN_EXPIRES_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>oidc_id_token_expires_at IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByOidcIdTokenExpiresAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.OIDC_ID_TOKEN_EXPIRES_AT, values);
    }

    /**
     * Fetch records that have <code>oidc_id_token_metadata BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfOidcIdTokenMetadata(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.OIDC_ID_TOKEN_METADATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>oidc_id_token_metadata IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByOidcIdTokenMetadata(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.OIDC_ID_TOKEN_METADATA, values);
    }

    /**
     * Fetch records that have <code>refresh_token_value BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfRefreshTokenValue(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.REFRESH_TOKEN_VALUE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>refresh_token_value IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByRefreshTokenValue(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.REFRESH_TOKEN_VALUE, values);
    }

    /**
     * Fetch records that have <code>refresh_token_issued_at BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfRefreshTokenIssuedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.REFRESH_TOKEN_ISSUED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>refresh_token_issued_at IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByRefreshTokenIssuedAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.REFRESH_TOKEN_ISSUED_AT, values);
    }

    /**
     * Fetch records that have <code>refresh_token_expires_at BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfRefreshTokenExpiresAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.REFRESH_TOKEN_EXPIRES_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>refresh_token_expires_at IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByRefreshTokenExpiresAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.REFRESH_TOKEN_EXPIRES_AT, values);
    }

    /**
     * Fetch records that have <code>refresh_token_metadata BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfRefreshTokenMetadata(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.REFRESH_TOKEN_METADATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>refresh_token_metadata IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByRefreshTokenMetadata(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.REFRESH_TOKEN_METADATA, values);
    }

    /**
     * Fetch records that have <code>user_code_value BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfUserCodeValue(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.USER_CODE_VALUE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_code_value IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByUserCodeValue(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.USER_CODE_VALUE, values);
    }

    /**
     * Fetch records that have <code>user_code_issued_at BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfUserCodeIssuedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.USER_CODE_ISSUED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_code_issued_at IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByUserCodeIssuedAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.USER_CODE_ISSUED_AT, values);
    }

    /**
     * Fetch records that have <code>user_code_expires_at BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfUserCodeExpiresAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.USER_CODE_EXPIRES_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_code_expires_at IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByUserCodeExpiresAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.USER_CODE_EXPIRES_AT, values);
    }

    /**
     * Fetch records that have <code>user_code_metadata BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfUserCodeMetadata(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.USER_CODE_METADATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_code_metadata IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByUserCodeMetadata(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.USER_CODE_METADATA, values);
    }

    /**
     * Fetch records that have <code>device_code_value BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfDeviceCodeValue(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.DEVICE_CODE_VALUE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>device_code_value IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByDeviceCodeValue(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.DEVICE_CODE_VALUE, values);
    }

    /**
     * Fetch records that have <code>device_code_issued_at BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfDeviceCodeIssuedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.DEVICE_CODE_ISSUED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>device_code_issued_at IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByDeviceCodeIssuedAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.DEVICE_CODE_ISSUED_AT, values);
    }

    /**
     * Fetch records that have <code>device_code_expires_at BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfDeviceCodeExpiresAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.DEVICE_CODE_EXPIRES_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>device_code_expires_at IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByDeviceCodeExpiresAt(LocalDateTime... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.DEVICE_CODE_EXPIRES_AT, values);
    }

    /**
     * Fetch records that have <code>device_code_metadata BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchRangeOfDeviceCodeMetadata(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Oauth2Authorization.OAUTH2_AUTHORIZATION.DEVICE_CODE_METADATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>device_code_metadata IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.Oauth2Authorization> fetchByDeviceCodeMetadata(byte[]... values) {
        return fetch(Oauth2Authorization.OAUTH2_AUTHORIZATION.DEVICE_CODE_METADATA, values);
    }
}
