/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.daos;


import cn.luixtech.passport.server.persistence.tables.SeqNumber;
import cn.luixtech.passport.server.persistence.tables.records.SeqNumberRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class SeqNumberDao extends DAOImpl<SeqNumberRecord, cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber, String> {

    /**
     * Create a new SeqNumberDao without any configuration
     */
    public SeqNumberDao() {
        super(SeqNumber.SEQ_NUMBER, cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber.class);
    }

    /**
     * Create a new SeqNumberDao with an attached configuration
     */
    @Autowired
    public SeqNumberDao(Configuration configuration) {
        super(SeqNumber.SEQ_NUMBER, cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber.class, configuration);
    }

    @Override
    public String getId(cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber> fetchRangeOfId(String lowerInclusive, String upperInclusive) {
        return fetchRange(SeqNumber.SEQ_NUMBER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber> fetchById(String... values) {
        return fetch(SeqNumber.SEQ_NUMBER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber fetchOneById(String value) {
        return fetchOne(SeqNumber.SEQ_NUMBER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber> fetchOptionalById(String value) {
        return fetchOptional(SeqNumber.SEQ_NUMBER.ID, value);
    }

    /**
     * Fetch records that have <code>table_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber> fetchRangeOfTableName(String lowerInclusive, String upperInclusive) {
        return fetchRange(SeqNumber.SEQ_NUMBER.TABLE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>table_name IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber> fetchByTableName(String... values) {
        return fetch(SeqNumber.SEQ_NUMBER.TABLE_NAME, values);
    }

    /**
     * Fetch records that have <code>max_seq_num BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber> fetchRangeOfMaxSeqNum(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SeqNumber.SEQ_NUMBER.MAX_SEQ_NUM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>max_seq_num IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SeqNumber> fetchByMaxSeqNum(Long... values) {
        return fetch(SeqNumber.SEQ_NUMBER.MAX_SEQ_NUM, values);
    }
}
