/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.daos;


import cn.luixtech.passport.server.persistence.tables.SpringSessionAttributes;
import cn.luixtech.passport.server.persistence.tables.records.SpringSessionAttributesRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SpringSessionAttributesDao extends DAOImpl<SpringSessionAttributesRecord, cn.luixtech.passport.server.persistence.tables.pojos.SpringSessionAttributes, Record2<String, String>> {

    /**
     * Create a new SpringSessionAttributesDao without any configuration
     */
    public SpringSessionAttributesDao() {
        super(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES, cn.luixtech.passport.server.persistence.tables.pojos.SpringSessionAttributes.class);
    }

    /**
     * Create a new SpringSessionAttributesDao with an attached configuration
     */
    @Autowired
    public SpringSessionAttributesDao(Configuration configuration) {
        super(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES, cn.luixtech.passport.server.persistence.tables.pojos.SpringSessionAttributes.class, configuration);
    }

    @Override
    public Record2<String, String> getId(cn.luixtech.passport.server.persistence.tables.pojos.SpringSessionAttributes object) {
        return compositeKeyRecord(object.getSessionPrimaryId(), object.getAttributeName());
    }

    /**
     * Fetch records that have <code>SESSION_PRIMARY_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SpringSessionAttributes> fetchRangeOfSessionPrimaryId(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>SESSION_PRIMARY_ID IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SpringSessionAttributes> fetchBySessionPrimaryId(String... values) {
        return fetch(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID, values);
    }

    /**
     * Fetch records that have <code>ATTRIBUTE_NAME BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SpringSessionAttributes> fetchRangeOfAttributeName(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ATTRIBUTE_NAME IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SpringSessionAttributes> fetchByAttributeName(String... values) {
        return fetch(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_NAME, values);
    }

    /**
     * Fetch records that have <code>ATTRIBUTE_BYTES BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SpringSessionAttributes> fetchRangeOfAttributeBytes(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ATTRIBUTE_BYTES IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.SpringSessionAttributes> fetchByAttributeBytes(byte[]... values) {
        return fetch(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES, values);
    }
}
