/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.daos;


import cn.luixtech.passport.server.persistence.tables.TableSeqNumber;
import cn.luixtech.passport.server.persistence.tables.records.TableSeqNumberRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class TableSeqNumberDao extends DAOImpl<TableSeqNumberRecord, cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber, String> {

    /**
     * Create a new TableSeqNumberDao without any configuration
     */
    public TableSeqNumberDao() {
        super(TableSeqNumber.TABLE_SEQ_NUMBER, cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber.class);
    }

    /**
     * Create a new TableSeqNumberDao with an attached configuration
     */
    @Autowired
    public TableSeqNumberDao(Configuration configuration) {
        super(TableSeqNumber.TABLE_SEQ_NUMBER, cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber.class, configuration);
    }

    @Override
    public String getId(cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber> fetchRangeOfId(String lowerInclusive, String upperInclusive) {
        return fetchRange(TableSeqNumber.TABLE_SEQ_NUMBER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber> fetchById(String... values) {
        return fetch(TableSeqNumber.TABLE_SEQ_NUMBER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber fetchOneById(String value) {
        return fetchOne(TableSeqNumber.TABLE_SEQ_NUMBER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber> fetchOptionalById(String value) {
        return fetchOptional(TableSeqNumber.TABLE_SEQ_NUMBER.ID, value);
    }

    /**
     * Fetch records that have <code>table_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber> fetchRangeOfTableName(String lowerInclusive, String upperInclusive) {
        return fetchRange(TableSeqNumber.TABLE_SEQ_NUMBER.TABLE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>table_name IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber> fetchByTableName(String... values) {
        return fetch(TableSeqNumber.TABLE_SEQ_NUMBER.TABLE_NAME, values);
    }

    /**
     * Fetch records that have <code>max_seq_num BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber> fetchRangeOfMaxSeqNum(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(TableSeqNumber.TABLE_SEQ_NUMBER.MAX_SEQ_NUM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>max_seq_num IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.TableSeqNumber> fetchByMaxSeqNum(Long... values) {
        return fetch(TableSeqNumber.TABLE_SEQ_NUMBER.MAX_SEQ_NUM, values);
    }
}
