/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.daos;


import cn.luixtech.passport.server.persistence.tables.UserPermission;
import cn.luixtech.passport.server.persistence.tables.records.UserPermissionRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class UserPermissionDao extends DAOImpl<UserPermissionRecord, cn.luixtech.passport.server.persistence.tables.pojos.UserPermission, String> {

    /**
     * Create a new UserPermissionDao without any configuration
     */
    public UserPermissionDao() {
        super(UserPermission.USER_PERMISSION, cn.luixtech.passport.server.persistence.tables.pojos.UserPermission.class);
    }

    /**
     * Create a new UserPermissionDao with an attached configuration
     */
    @Autowired
    public UserPermissionDao(Configuration configuration) {
        super(UserPermission.USER_PERMISSION, cn.luixtech.passport.server.persistence.tables.pojos.UserPermission.class, configuration);
    }

    @Override
    public String getId(cn.luixtech.passport.server.persistence.tables.pojos.UserPermission object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.UserPermission> fetchRangeOfId(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserPermission.USER_PERMISSION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.UserPermission> fetchById(String... values) {
        return fetch(UserPermission.USER_PERMISSION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.luixtech.passport.server.persistence.tables.pojos.UserPermission fetchOneById(String value) {
        return fetchOne(UserPermission.USER_PERMISSION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<cn.luixtech.passport.server.persistence.tables.pojos.UserPermission> fetchOptionalById(String value) {
        return fetchOptional(UserPermission.USER_PERMISSION.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.UserPermission> fetchRangeOfUserId(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserPermission.USER_PERMISSION.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.UserPermission> fetchByUserId(String... values) {
        return fetch(UserPermission.USER_PERMISSION.USER_ID, values);
    }

    /**
     * Fetch records that have <code>permission BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.UserPermission> fetchRangeOfPermission(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserPermission.USER_PERMISSION.PERMISSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>permission IN (values)</code>
     */
    public List<cn.luixtech.passport.server.persistence.tables.pojos.UserPermission> fetchByPermission(String... values) {
        return fetch(UserPermission.USER_PERMISSION.PERMISSION, values);
    }
}
