/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.DataDict;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DataDictRecord extends UpdatableRecordImpl<DataDictRecord> implements Record6<String, String, String, String, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>luix-passport.data_dict.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>luix-passport.data_dict.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>luix-passport.data_dict.category_code</code>.
     */
    public void setCategoryCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>luix-passport.data_dict.category_code</code>.
     */
    public String getCategoryCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>luix-passport.data_dict.dict_code</code>.
     */
    public void setDictCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>luix-passport.data_dict.dict_code</code>.
     */
    public String getDictCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>luix-passport.data_dict.dict_name</code>.
     */
    public void setDictName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>luix-passport.data_dict.dict_name</code>.
     */
    public String getDictName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>luix-passport.data_dict.desc</code>.
     */
    public void setDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>luix-passport.data_dict.desc</code>.
     */
    public String getDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>luix-passport.data_dict.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>luix-passport.data_dict.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, String, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, String, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return DataDict.DATA_DICT.ID;
    }

    @Override
    public Field<String> field2() {
        return DataDict.DATA_DICT.CATEGORY_CODE;
    }

    @Override
    public Field<String> field3() {
        return DataDict.DATA_DICT.DICT_CODE;
    }

    @Override
    public Field<String> field4() {
        return DataDict.DATA_DICT.DICT_NAME;
    }

    @Override
    public Field<String> field5() {
        return DataDict.DATA_DICT.DESC;
    }

    @Override
    public Field<Boolean> field6() {
        return DataDict.DATA_DICT.ENABLED;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCategoryCode();
    }

    @Override
    public String component3() {
        return getDictCode();
    }

    @Override
    public String component4() {
        return getDictName();
    }

    @Override
    public String component5() {
        return getDesc();
    }

    @Override
    public Boolean component6() {
        return getEnabled();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCategoryCode();
    }

    @Override
    public String value3() {
        return getDictCode();
    }

    @Override
    public String value4() {
        return getDictName();
    }

    @Override
    public String value5() {
        return getDesc();
    }

    @Override
    public Boolean value6() {
        return getEnabled();
    }

    @Override
    public DataDictRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public DataDictRecord value2(String value) {
        setCategoryCode(value);
        return this;
    }

    @Override
    public DataDictRecord value3(String value) {
        setDictCode(value);
        return this;
    }

    @Override
    public DataDictRecord value4(String value) {
        setDictName(value);
        return this;
    }

    @Override
    public DataDictRecord value5(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public DataDictRecord value6(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public DataDictRecord values(String value1, String value2, String value3, String value4, String value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataDictRecord
     */
    public DataDictRecord() {
        super(DataDict.DATA_DICT);
    }

    /**
     * Create a detached, initialised DataDictRecord
     */
    public DataDictRecord(String id, String categoryCode, String dictCode, String dictName, String desc, Boolean enabled) {
        super(DataDict.DATA_DICT);

        setId(id);
        setCategoryCode(categoryCode);
        setDictCode(dictCode);
        setDictName(dictName);
        setDesc(desc);
        setEnabled(enabled);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DataDictRecord
     */
    public DataDictRecord(cn.luixtech.passport.server.persistence.tables.pojos.DataDict value) {
        super(DataDict.DATA_DICT);

        if (value != null) {
            setId(value.getId());
            setCategoryCode(value.getCategoryCode());
            setDictCode(value.getDictCode());
            setDictName(value.getDictName());
            setDesc(value.getDesc());
            setEnabled(value.getEnabled());
            resetChangedOnNotNull();
        }
    }
}
