/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables.records;


import cn.luixtech.passport.server.persistence.tables.TeamUser;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TeamUserRecord extends UpdatableRecordImpl<TeamUserRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>luix-passport.team_user.team_id</code>.
     */
    public void setTeamId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>luix-passport.team_user.team_id</code>.
     */
    public String getTeamId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>luix-passport.team_user.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>luix-passport.team_user.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TeamUser.TEAM_USER.TEAM_ID;
    }

    @Override
    public Field<String> field2() {
        return TeamUser.TEAM_USER.USER_ID;
    }

    @Override
    public String component1() {
        return getTeamId();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public String value1() {
        return getTeamId();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public TeamUserRecord value1(String value) {
        setTeamId(value);
        return this;
    }

    @Override
    public TeamUserRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public TeamUserRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamUserRecord
     */
    public TeamUserRecord() {
        super(TeamUser.TEAM_USER);
    }

    /**
     * Create a detached, initialised TeamUserRecord
     */
    public TeamUserRecord(String teamId, String userId) {
        super(TeamUser.TEAM_USER);

        setTeamId(teamId);
        setUserId(userId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TeamUserRecord
     */
    public TeamUserRecord(cn.luixtech.passport.server.persistence.tables.pojos.TeamUser value) {
        super(TeamUser.TEAM_USER);

        if (value != null) {
            setTeamId(value.getTeamId());
            setUserId(value.getUserId());
            resetChangedOnNotNull();
        }
    }
}
