spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luix-passport?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password:
  liquibase:
    enabled: true
    drop-first: true # reset database
server:
  forward-headers-strategy: framework # Resolved http CORS block issue on prod env
# ===================================================================
# Application specific properties
# ===================================================================
application:
  allowed-cors:
    mappings:
      "[/api/**]": http://passport.luixtech.cn
  company:
    force-to-https: true