# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-test.yml if you use the "test" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/3.2.0/reference/html/application-properties.html#application-properties
# ===================================================================
server:
  port: 4001
management: # Management http server configuration, used by ManagementServerProperties
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - info
          - health
          - beans
          - mappings
          - httptrace
          - shutdown
          - auditevents
          - scheduledtasks
          - loggers
          - prometheus
          - threaddump
          - liquibase
          - luixopenapigroups
    endpoint:
      health: # used by HealthEndpointProperties, Note: it will show health details if it has the access token by Ajax
        enabled: true
        show-details: WHEN_AUTHORIZED
      httptrace:
        enabled: true
      shutdown:
        enabled: true # explicitly enable
    health:
      mail:
        enabled: false
    metrics:
      tags:
        application: ${spring.application.name}
spring:
  application:
    name: luix-passport-server
  profiles:
    # The commented value for `active` can be replaced with valid spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: test
  banner:
    location: classpath:config/banner-company.txt
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  security:
    oauth2:
      client:
        registration:
          google-idp: # https://accounts.google.com/.well-known/openid-configuration
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:16dc9a9c9866efc8ea26}
            client-secret: ${GITHUB_CLIENT_SECRET:48d2df23b64901f248e8a156eedac932ab579054}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login
  liquibase:
    enabled: false
    change-log: classpath:config/liquibase/master.xml
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.jooq.tools.LoggerListener: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
springdoc: # https://springdoc.org/#migrating-from-springfox
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    tags-sorter: alpha
# ===================================================================
# Luix framework specific properties
# ===================================================================
luix:
  api-docs:
    api-include-pattern: /api/**
    open-api-include-pattern: /open-api/**
    management-include-pattern: /management/**
    api-title: LUI️✘ Passport Server API
    open-api-title: LUI️✘ Passport Server Open API
    management-title: LUI️✘ Passport Server Management API
    version: ${spring.application.name}
    terms-of-service-url:
    contact-name: Louis
    contact-url:
    contact-email: louis@luixtech.cn
    license: Unlicensed
    license-url:
  aop-logging:
    enabled: true
    method-whitelist-mode: false
  elapsed-time-logging:
    enabled: true
    slow-execution-threshold: 300 # unit: ms
  ribbon:
    # comma separated list of profiles to show a ribbon on the GUI
    display-on-active-profiles: dev,test,demo
