# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/3.1.0/reference/html/application-properties.html#application-properties
# ===================================================================
app:
    id: luix-sso-server
    name: luix-sso-server
    version: 1.0.0
    companyName: www.luixtech.com
management: # Management http server configuration, used by ManagementServerProperties
    endpoints:
        web:
            base-path: /management
            exposure:
                include:
                    - configprops
                    - env
                    - info
                    - health
                    - beans
                    - mappings
                    - httptrace
                    - shutdown
                    - auditevents
                    - scheduledtasks
                    - loggers
                    - prometheus
                    - threaddump
                    - liquibase
                    - luixopenapigroups
    endpoint:
        health:
            enabled: true
            show-details: always
        metrics:
            enabled: true
        prometheus:
            enabled: true
    metrics:
        tags:
            application: ${app.id}
spring:
    application:
        name: ${app.id}
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: dev
    web:
        locale: zh_CN # default locale
    messages:
        basename: i18n/messages,i18n/luix-messages
        fallback-to-system-locale: false
    thymeleaf: #ThymeleafAutoConfiguration
        mode: HTML
    banner:
        location: classpath:config/banner-company.txt
server:
    # It can be overridden by `--server.port` value passed in the commandline or `-Dserver.port` set in `JAVA_OPTS`
    port: 8080
    servlet:
        session:
            cookie:
                name: ${spring.application.name}
logging:
    level:
        root: INFO
        org.springframework.boot.devtools.autoconfigure: INFO
        org.apache: WARN
        org.mongodb.driver: WARN
        sun.rmi: WARN
        jdk.event.security: WARN
springdoc:
    api-docs:
        enabled: true
    show-actuator: true
    swagger-ui:
        tags-sorter: alpha
# ===================================================================
# Shiro properties
# ===================================================================
shiro:
    web:
        enabled: true
    enabled: true
    userNativeSessionManager: true
    loginUrl: /open-api/login
    successUrl: /
    unauthorizedUrl: /unauthorized
# ===================================================================
# Luix framework specific properties
# ===================================================================
luix:
    sso:
        server:
            enabled: true
            filterChainDefinitionMap: # Bind Map refer to https://github.com/spring-projects/spring-boot/issues/13404#issuecomment-395307439
                "[/favicon.ico]": anon
                "[/images/**]": anon
                "[/management/**]": anon
                "[/open-api/**]": anon
                "[/login.html]": authc # Need to support redirect to target URL for POSTs from the login form
                "[/api/**]": user
                "[/logout]": logout
                "[/**]": user
    api-docs:
        api-include-pattern: /api/**
        open-api-include-pattern: /open-api/**
        management-include-pattern: /management/**
        api-title: Luix SSO Server API
        open-api-title: Luix SSO Server Open API
        management-title: Luix SSO Server Management API
        version: ${app.version}
        terms-of-service-url:
        contact-name: louis
        contact-url:
        contact-email: louis@luixtech.com
        contact-mobile: 13800138000
        license: unlicensed
        license-url:
# ===================================================================
# Application specific properties
# ===================================================================