spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luix-passport?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password:
  liquibase:
    enabled: true
    drop-first: true # reset database
# ===================================================================
# Application specific properties
# ===================================================================
application:
  allowed-cors:
    mappings:
      "[/api/**]": http://127.0.0.1:4001