# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: luix-passport
services:
  luix-passport-server:
    image: luix-passport-server
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=test
#      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
#      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
    ports:
      - 127.0.0.1:4001:4001
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:4001/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    extends:
      file: ./mysql.yml
      service: luix-mysql

