services:
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      # init-letsencrypt.sh will generate certbot files to docker/config/certbot
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    #   You need to make sure that nginx reloads the newly obtained certificates
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    #   This will check if your certificate is up for renewal every 12 hours as recommended by Let’s Encrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
