# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
# Refer to https://beta.nginxconfig.io/?0.domain=passport.luixtech.cn&0.php=false&0.proxy&0.proxy_pass=http:%2F%2F127.0.0.1:4001
name: luix
services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/app:/etc/nginx/conf.d
      # init-letsencrypt.sh will generate certbot files to docker/config/certbot
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    #   You need to make sure that nginx reloads the newly obtained certificates
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:v2.7.0
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    #   This will check if your certificate is up for renewal every 12 hours as recommended by Let’s Encrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
