# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: luix-passport
services:
  server:
    image: luix-passport-server
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      # Note: It can NOT use localhost as the database URL
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/luix-passport?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 4001:4001
#      - 127.0.0.1:4001:4001
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:4001/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
