# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/3.1.0/reference/html/application-properties.html#application-properties
# ===================================================================
server:
  port: 4001
management: # Management http server configuration, used by ManagementServerProperties
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - info
          - health
          - metrics
          - prometheus
          - luixopenapigroups
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: luix-passport-server
  profiles:
    # The commented value for `active` can be replaced with valid spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: test
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
# Created EmbeddedDatabase bean manually in AuthorizationServerConfiguration.class, problem refer to https://stackoverflow.com/questions/41873372/execute-multiple-scripts-on-application-startup
#    url: jdbc:h2:mem:passport;INIT=RUNSCRIPT FROM 'classpath:/org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql'\;RUNSCRIPT FROM 'classpath:/org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql'\;RUNSCRIPT FROM 'classpath:/org/springframework/security/oauth2/server/authorization/oauth2-authorization-consent-schema.sql'
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:0f25e4d118b8caa67371}
            client-secret: ${GITHUB_CLIENT_SECRET:b4eba530555b66efc49d4e4da558d59006ec873f}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login
logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
springdoc: # https://springdoc.org/#migrating-from-springfox
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    tags-sorter: alpha
# ===================================================================
# Luix framework specific properties
# ===================================================================
luix:
  api-docs:
    api-include-pattern: /api/**
    open-api-include-pattern: /open-api/**
    management-include-pattern: /management/**
    api-title: LUI️✘ Passport Server API
    open-api-title: LUI️✘ Passport Server API
    management-title: LUI️✘ Passport Server Management API
    version: ${spring.application.name}
    terms-of-service-url:
    contact-name: Louis
    contact-url:
    contact-email: louis@luixtech.cn
    license: Unlicensed
    license-url:
  aop-logging:
    enabled: true
    method-whitelist-mode: false
  elapsed-time-logging:
    enabled: true
    slow-execution-threshold: 300 # unit: ms
  ribbon:
    # comma separated list of profiles to show a ribbon on the GUI
    display-on-active-profiles: dev,test,demo
