/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables;


import cn.luixtech.passport.server.persistence.Keys;
import cn.luixtech.passport.server.persistence.LuixPassport;
import cn.luixtech.passport.server.persistence.tables.records.UserLoginRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLogin extends TableImpl<UserLoginRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>luix-passport.user_login</code>
     */
    public static final UserLogin USER_LOGIN = new UserLogin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserLoginRecord> getRecordType() {
        return UserLoginRecord.class;
    }

    /**
     * The column <code>luix-passport.user_login.id</code>.
     */
    public final TableField<UserLoginRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>luix-passport.user_login.user_id</code>.
     */
    public final TableField<UserLoginRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>luix-passport.user_login.logged_time</code>.
     */
    public final TableField<UserLoginRecord, LocalDateTime> LOGGED_TIME = createField(DSL.name("logged_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>luix-passport.user_login.location</code>.
     */
    public final TableField<UserLoginRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>luix-passport.user_login.ip</code>.
     */
    public final TableField<UserLoginRecord, String> IP = createField(DSL.name("ip"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>luix-passport.user_login.os</code>.
     */
    public final TableField<UserLoginRecord, String> OS = createField(DSL.name("os"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>luix-passport.user_login.browser</code>.
     */
    public final TableField<UserLoginRecord, String> BROWSER = createField(DSL.name("browser"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private UserLogin(Name alias, Table<UserLoginRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserLogin(Name alias, Table<UserLoginRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>luix-passport.user_login</code> table reference
     */
    public UserLogin(String alias) {
        this(DSL.name(alias), USER_LOGIN);
    }

    /**
     * Create an aliased <code>luix-passport.user_login</code> table reference
     */
    public UserLogin(Name alias) {
        this(alias, USER_LOGIN);
    }

    /**
     * Create a <code>luix-passport.user_login</code> table reference
     */
    public UserLogin() {
        this(DSL.name("user_login"), null);
    }

    public <O extends Record> UserLogin(Table<O> child, ForeignKey<O, UserLoginRecord> key) {
        super(child, key, USER_LOGIN);
    }

    @Override
    public Schema getSchema() {
        return LuixPassport.LUIX_PASSPORT;
    }

    @Override
    public UniqueKey<UserLoginRecord> getPrimaryKey() {
        return Keys.KEY_USER_LOGIN_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserLoginRecord>> getKeys() {
        return Arrays.<UniqueKey<UserLoginRecord>>asList(Keys.KEY_USER_LOGIN_PRIMARY);
    }

    @Override
    public List<ForeignKey<UserLoginRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserLoginRecord, ?>>asList(Keys.FK_USER_LOGIN_USER_ID);
    }

    private transient User _user;

    public User user() {
        if (_user == null)
            _user = new User(this, Keys.FK_USER_LOGIN_USER_ID);

        return _user;
    }

    @Override
    public UserLogin as(String alias) {
        return new UserLogin(DSL.name(alias), this);
    }

    @Override
    public UserLogin as(Name alias) {
        return new UserLogin(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserLogin rename(String name) {
        return new UserLogin(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserLogin rename(Name name) {
        return new UserLogin(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, LocalDateTime, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
