/*
 * This file is generated by jOOQ.
 */
package cn.luixtech.passport.server.persistence.tables;


import cn.luixtech.passport.server.persistence.Keys;
import cn.luixtech.passport.server.persistence.LuixPassport;
import cn.luixtech.passport.server.persistence.tables.records.UserAuthorityRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAuthority extends TableImpl<UserAuthorityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>luix-passport.user_authority</code>
     */
    public static final UserAuthority USER_AUTHORITY = new UserAuthority();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAuthorityRecord> getRecordType() {
        return UserAuthorityRecord.class;
    }

    /**
     * The column <code>luix-passport.user_authority.user_id</code>.
     */
    public final TableField<UserAuthorityRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>luix-passport.user_authority.authority</code>.
     */
    public final TableField<UserAuthorityRecord, String> AUTHORITY = createField(DSL.name("authority"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private UserAuthority(Name alias, Table<UserAuthorityRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserAuthority(Name alias, Table<UserAuthorityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>luix-passport.user_authority</code> table
     * reference
     */
    public UserAuthority(String alias) {
        this(DSL.name(alias), USER_AUTHORITY);
    }

    /**
     * Create an aliased <code>luix-passport.user_authority</code> table
     * reference
     */
    public UserAuthority(Name alias) {
        this(alias, USER_AUTHORITY);
    }

    /**
     * Create a <code>luix-passport.user_authority</code> table reference
     */
    public UserAuthority() {
        this(DSL.name("user_authority"), null);
    }

    public <O extends Record> UserAuthority(Table<O> child, ForeignKey<O, UserAuthorityRecord> key) {
        super(child, key, USER_AUTHORITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : LuixPassport.LUIX_PASSPORT;
    }

    @Override
    public UniqueKey<UserAuthorityRecord> getPrimaryKey() {
        return Keys.KEY_USER_AUTHORITY_PRIMARY;
    }

    @Override
    public List<ForeignKey<UserAuthorityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_USER_AUTHORITY_USER_ID);
    }

    private transient User _user;

    /**
     * Get the implicit join path to the <code>luix-passport.user</code> table.
     */
    public User user() {
        if (_user == null)
            _user = new User(this, Keys.FK_USER_AUTHORITY_USER_ID);

        return _user;
    }

    @Override
    public UserAuthority as(String alias) {
        return new UserAuthority(DSL.name(alias), this);
    }

    @Override
    public UserAuthority as(Name alias) {
        return new UserAuthority(alias, this);
    }

    @Override
    public UserAuthority as(Table<?> alias) {
        return new UserAuthority(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAuthority rename(String name) {
        return new UserAuthority(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAuthority rename(Name name) {
        return new UserAuthority(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAuthority rename(Table<?> name) {
        return new UserAuthority(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
