/*
 * This file is generated by jOOQ.
 */
package com.luixtech.sso.server.persistence;


import com.luixtech.sso.server.persistence.tables.User;
import com.luixtech.sso.server.persistence.tables.UserPermission;
import com.luixtech.sso.server.persistence.tables.UserRole;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LuixSso extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>luix-sso</code>
     */
    public static final LuixSso LUIX_SSO = new LuixSso();

    /**
     * The table <code>luix-sso.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>luix-sso.user_permission</code>.
     */
    public final UserPermission USER_PERMISSION = UserPermission.USER_PERMISSION;

    /**
     * The table <code>luix-sso.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private LuixSso() {
        super("luix-sso", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            User.USER,
            UserPermission.USER_PERMISSION,
            UserRole.USER_ROLE);
    }
}
