# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/3.1.0/reference/html/application-properties.html#application-properties
# ===================================================================
server:
  port: 4003
management: # Management http server configuration, used by ManagementServerProperties
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - info
          - health
          - metrics
          - prometheus
          - luixopenapigroups
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: luix-passport-client
  profiles:
    # The commented value for `active` can be replaced with valid spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: test
  thymeleaf:
    cache: false
  banner:
    location: classpath:config/banner-company.txt
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:4001
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-name: messaging-client-oidc
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:4003/login/oauth2/code/{registrationId}"
            scope: openid, profile
          messaging-client-authorization-code:
            provider: spring
            client-id: messaging-client
            client-name: messaging-client-authorization-code
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:4003/authorized"
            scope: message.read,message.write
          messaging-client-client-credentials:
            provider: spring
            client-id: messaging-client
            client-name: messaging-client-client-credentials
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: message.read,message.write
          messaging-client-device-code:
            provider: spring
            client-id: device-messaging-client
            client-name: messaging-client-device-code
            client-authentication-method: none
            authorization-grant-type: urn:ietf:params:oauth:grant-type:device_code
            scope: message.read,message.write
logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
springdoc: # https://springdoc.org/#migrating-from-springfox
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    tags-sorter: alpha
# ===================================================================
# Luix framework specific properties
# ===================================================================
luix:
  api-docs:
    api-include-pattern: /api/**
    open-api-include-pattern: /open-api/**
    management-include-pattern: /management/**
    api-title: LUI️✘ Passport Client API
    open-api-title: LUI️✘ Passport Client API
    management-title: LUI️✘ Passport Client Management API
    version: ${spring.application.name}
    terms-of-service-url:
    contact-name: Louis
    contact-url:
    contact-email: louis@luixtech.cn
    license: Unlicensed
    license-url:
  aop-logging:
    enabled: true
    method-whitelist-mode: false
  elapsed-time-logging:
    enabled: true
    slow-execution-threshold: 300 # unit: ms
  ribbon:
    # comma separated list of profiles to show a ribbon on the GUI
    display-on-active-profiles: dev,test,demo
# ===================================================================
# Application specific properties
# ===================================================================
application:
  url:
    oauth-server-messages: http://127.0.0.1:4001/api/messages
    resource-server-messages: http://127.0.0.1:4002/api/messages